param(
  [Parameter(Mandatory = $true)]
  [string]$StoryId,

  [Parameter(Mandatory = $true)]
  [string]$GateEvidenceFile,

  [Parameter(Mandatory = $false)]
  [string]$UatResultsFile,

  [Parameter(Mandatory = $false)]
  [string]$Notes = ""
)

$ErrorActionPreference = "Stop"
Set-StrictMode -Version Latest

$repoRoot = (Get-Location).Path

if ([string]::IsNullOrWhiteSpace($UatResultsFile)) {
  $UatResultsFile = Join-Path $repoRoot "docs/stories/STORY-$StoryId-UAT-RESULTS.md"
}

if (-not (Test-Path $GateEvidenceFile)) {
  throw "Gate evidence file not found: $GateEvidenceFile"
}

$gateContent = Get-Content -Path $GateEvidenceFile -Raw
$timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"

$section = @()
$section += ""
$section += "---"
$section += ""
$section += "## Automated Gate Evidence Sync ($timestamp)"
$section += ""
$section += "Source: $GateEvidenceFile"
$section += ""
$section += '```text'
$section += $gateContent.TrimEnd()
$section += '```'

if (-not [string]::IsNullOrWhiteSpace($Notes)) {
  $section += ""
  $section += "### Notes"
  $section += ""
  $section += $Notes
}

if (-not (Test-Path $UatResultsFile)) {
  $header = @()
  $header += "# Story $StoryId UAT Results"
  $header += ""
  $header += "_Generated by scripts/workflow/generate-story-evidence.ps1_"
  $header += ""
  Set-Content -Path $UatResultsFile -Value ($header -join [Environment]::NewLine) -Encoding UTF8
}

Add-Content -Path $UatResultsFile -Value (($section -join [Environment]::NewLine) + [Environment]::NewLine) -Encoding UTF8

Write-Host "Updated: $UatResultsFile"
